# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constr.xdc

# IP: ip/prgrom/prgrom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prgrom || ORIG_REF_NAME==prgrom} -quiet] -quiet

# IP: ip/RAM/RAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM || ORIG_REF_NAME==RAM} -quiet] -quiet

# IP: ip/cpuclk/cpuclk.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpuclk || ORIG_REF_NAME==cpuclk} -quiet] -quiet

# XDC: ip/prgrom/prgrom_ooc.xdc

# XDC: ip/RAM/RAM_ooc.xdc

# XDC: ip/cpuclk/cpuclk_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cpuclk || ORIG_REF_NAME==cpuclk} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/cpuclk/cpuclk.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cpuclk || ORIG_REF_NAME==cpuclk} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/cpuclk/cpuclk_ooc.xdc
